![Königsweg Logo](../img/koenigsweg_150.png)

<span style="font-size: small;float: right;">&copy; 2015-2018 Alexander C.S. Hendorf, <a href="http://koenigsweg.com">Königsweg GmbH</a>, Mannheim </span>

---

# Data Wrangling and Visualisation with Juypter and Pandas

---

# Operations

---

In [1]:
import pandas as pd
import random
import numpy as np
import matplotlib
% matplotlib inline

In [2]:
df = pd.read_json('../data/sampledf.json')
df.index = ["R{:02d}".format(i) for i in range(len(df))]
df.columns = ["C{:02d}".format(i) for i in range(len(df.columns))]
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09
R00   79   19   21   99   35   59   44   25   75   58
R01   25   39   89   66    9   41    6   69   63    3
R02   37   64   31   69   61   97    5   11   76   57
R03   74   61  100    6   58   80   95   50   15   51
R04   79   60   83   85   16    5   16   69    5   20
R05   45   26   73   73  100   60   21   19   95   12
R06   12   29   18   98   62   68   92   29   74   96
R07   36   32   22    4   66   25   63   51   59   14
R08   55   53   89   13   84   87   74    3    2   64
R09   46   74   36   54   21   12   68   33   80   25

### Adding and deleting Series in a DataFrame

In [3]:
df['C10'] = [random.randint(1, 100) for i in range(len(df))]
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58   71
R01   25   39   89   66    9   41    6   69   63    3   98
R02   37   64   31   69   61   97    5   11   76   57   65
R03   74   61  100    6   58   80   95   50   15   51   53
R04   79   60   83   85   16    5   16   69    5   20   60
R05   45   26   73   73  100   60   21   19   95   12    9
R06   12   29   18   98   62   68   92   29   74   96   83
R07   36   32   22    4   66   25   63   51   59   14   32
R08   55   53   89   13   84   87   74    3    2   64   73
R09   46   74   36   54   21   12   68   33   80   25   32

In [4]:
# caveat when adding a Series:
new_series = pd.Series(list([random.randint(1, 100) for i in range(len(df))]))
new_series

0    15
1    85
2    37
3    63
4    40
5    41
6    13
7     8
8    54
9    16
dtype: int64

In [5]:
df['C10'] = new_series
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58  NaN
R01   25   39   89   66    9   41    6   69   63    3  NaN
R02   37   64   31   69   61   97    5   11   76   57  NaN
R03   74   61  100    6   58   80   95   50   15   51  NaN
R04   79   60   83   85   16    5   16   69    5   20  NaN
R05   45   26   73   73  100   60   21   19   95   12  NaN
R06   12   29   18   98   62   68   92   29   74   96  NaN
R07   36   32   22    4   66   25   63   51   59   14  NaN
R08   55   53   89   13   84   87   74    3    2   64  NaN
R09   46   74   36   54   21   12   68   33   80   25  NaN

In [6]:
# adding a new Series: mind the index of the the DF
new_series.index = df.index
new_series

R00    15
R01    85
R02    37
R03    63
R04    40
R05    41
R06    13
R07     8
R08    54
R09    16
dtype: int64

In [7]:
df['C10'] = new_series
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58   15
R01   25   39   89   66    9   41    6   69   63    3   85
R02   37   64   31   69   61   97    5   11   76   57   37
R03   74   61  100    6   58   80   95   50   15   51   63
R04   79   60   83   85   16    5   16   69    5   20   40
R05   45   26   73   73  100   60   21   19   95   12   41
R06   12   29   18   98   62   68   92   29   74   96   13
R07   36   32   22    4   66   25   63   51   59   14    8
R08   55   53   89   13   84   87   74    3    2   64   54
R09   46   74   36   54   21   12   68   33   80   25   16

In [8]:
df['C11'] = new_series
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10  C11
R00   79   19   21   99   35   59   44   25   75   58   15   15
R01   25   39   89   66    9   41    6   69   63    3   85   85
R02   37   64   31   69   61   97    5   11   76   57   37   37
R03   74   61  100    6   58   80   95   50   15   51   63   63
R04   79   60   83   85   16    5   16   69    5   20   40   40
R05   45   26   73   73  100   60   21   19   95   12   41   41
R06   12   29   18   98   62   68   92   29   74   96   13   13
R07   36   32   22    4   66   25   63   51   59   14    8    8
R08   55   53   89   13   84   87   74    3    2   64   54   54
R09   46   74   36   54   21   12   68   33   80   25   16   16

In [9]:
del df['C11']
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58   15
R01   25   39   89   66    9   41    6   69   63    3   85
R02   37   64   31   69   61   97    5   11   76   57   37
R03   74   61  100    6   58   80   95   50   15   51   63
R04   79   60   83   85   16    5   16   69    5   20   40
R05   45   26   73   73  100   60   21   19   95   12   41
R06   12   29   18   98   62   68   92   29   74   96   13
R07   36   32   22    4   66   25   63   51   59   14    8
R08   55   53   89   13   84   87   74    3    2   64   54
R09   46   74   36   54   21   12   68   33   80   25   16

In [10]:
del df['C12']

KeyError: 'C12'

In [11]:
# avoid KeyErrors if unsure Series exists
df.drop(['C12'], errors='ignore')

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58   15
R01   25   39   89   66    9   41    6   69   63    3   85
R02   37   64   31   69   61   97    5   11   76   57   37
R03   74   61  100    6   58   80   95   50   15   51   63
R04   79   60   83   85   16    5   16   69    5   20   40
R05   45   26   73   73  100   60   21   19   95   12   41
R06   12   29   18   98   62   68   92   29   74   96   13
R07   36   32   22    4   66   25   63   51   59   14    8
R08   55   53   89   13   84   87   74    3    2   64   54
R09   46   74   36   54   21   12   68   33   80   25   16

In [12]:
# getting a subset is simpler than delting many columns
dfs = df.loc[:, ['C03', 'C05']]
dfs

C03  C05
R00   99   59
R01   66   41
R02   69   97
R03    6   80
R04   85    5
R05   73   60
R06   98   68
R07    4   25
R08   13   87
R09   54   12

### Mangle your data

**recall: NumPy Broadcasting**

In [13]:
a = np.random.rand(3,1)
a

array([[ 0.14322079],
       [ 0.85098627],
       [ 0.10118384]])

In [14]:
b = np.random.rand(3,1)
b

array([[ 0.00314335],
       [ 0.51521778],
       [ 0.37823933]])

In [15]:
a + b

array([[ 0.14636414],
       [ 1.36620404],
       [ 0.47942317]])

In [16]:
a - b

array([[ 0.14007744],
       [ 0.33576849],
       [-0.2770555 ]])

In [17]:
a * b

array([[ 0.00045019],
       [ 0.43844325],
       [ 0.03827171]])

In [18]:
a / b

array([[ 45.56312289],
       [  1.65170207],
       [  0.26751274]])

In [19]:
a + 7

array([[ 7.14322079],
       [ 7.85098627],
       [ 7.10118384]])

In [20]:
b // 2

array([[ 0.],
       [ 0.],
       [ 0.]])

In [21]:
a % 2 == 0

array([[False],
       [False],
       [False]], dtype=bool)

In [22]:
a * [4, 5]

array([[ 0.57288315,  0.71610394],
       [ 3.40394507,  4.25493133],
       [ 0.40473536,  0.5059192 ]])

### Broadcasting in Pandas

In [23]:
sales_data = pd.read_json('../data/blooth_sales_data.json',
                              convert_dates=['birthday', 'orderdate']
                              )
sales_data.head(5)

birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene 2016-10-02 08:21:20.544643   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  
0          Star Wars      11.81     27  
1        PlayStation     284.71      1  
2             banana      10.00     49  
3    Thriller record      16.77     48  
4  Harry Potter book       5.65      4

In [24]:
sales_data['turnover'] = sales_data['unitprice'] * sales_data['units']
sales_data.head(5)

birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene 2016-10-02 08:21:20.544643   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  
0          Star Wars      11.81     27    318.87  
1        PlayStation     284.71      1    284.71  
2             banana      10.00     49    490.00  
3    Thriller record      16.77     48    804.96  
4  Harry Potter book       5.65      4     22.60

In [25]:
sales_data['turnover'].mean()

59915.647646055448

In [26]:
sales_data.mean()

unitprice     2329.681343
units           25.808102
turnover     59915.647646
dtype: float64

In [27]:
sales_data['turnover'].sum()

140502193.73000002

In [28]:
sales_data['turnover'].median()

532.13999999999999

In [29]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2345 entries, 0 to 2344
Data columns (total 8 columns):
birthday     2345 non-null datetime64[ns]
customer     2345 non-null object
name         2345 non-null object
orderdate    2345 non-null datetime64[ns]
product      2345 non-null object
unitprice    2345 non-null float64
units        2345 non-null int64
turnover     2345 non-null float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(3)
memory usage: 146.6+ KB


### Excercise

Calculate the mean without using .mean

In [ ]:
# your code here


In [31]:
%load ../solutions/301.py


59915.647646055448

Find the oldest customer (bithday)

In [ ]:
# your code here


In [33]:
%load ../solutions/302.py


array(['Lesa'], dtype=object)

### Functions with **`.map(), .apply() .applymap()`**

In [30]:
# map for Series
sales_data['year'] = sales_data['orderdate'].map(lambda x: x.year)
sales_data.head(5)

birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene 2016-10-02 08:21:20.544643   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  
0          Star Wars      11.81     27    318.87  2016  
1        PlayStation     284.71      1    284.71  2016  
2             banana      10.00     49    490.00  2016  
3    Thriller record      16.77     48    804.96  2016  
4  Harry Potter book       5.65      4     22.60  2016

In [31]:
# map for Series
sales_data['month'] = sales_data['orderdate'].map(lambda x: x.month)
sales_data.head(5)

birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene 2016-10-02 08:21:20.544643   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month  
0          Star Wars      11.81     27    318.87  2016     10  
1        PlayStation     284.71      1    284.71  2016      9  
2             banana      10.00     49    490.00  2016     10  
3    Thriller record      16.77     48    804.96  2016     10  
4  Harry Potter book       5.65      4     22.60  2016     10

In [32]:
# combine multiple columns
sales_data['year-month'] = sales_data['year'].map(
    str) + sales_data['month'].map(lambda x: "-{:02d}".format(x))

In [33]:
sales_data.head(5)

birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene 2016-10-02 08:21:20.544643   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month year-month  
0          Star Wars      11.81     27    318.87  2016     10    2016-10  
1        PlayStation     284.71      1    284.71  2016      9    2016-09  
2             banana      10.00     49    490.00  2016     10    2016-10  
3    Thriller record      16.77     48    804.96  2016     10    2016-10  
4  Harry Potter book       5.65      4     22.60  2016     10    2016-10

In [34]:
sales_data[['unitprice', 'units']]

unitprice  units
0         11.81     27
1        284.71      1
2         10.00     49
3         16.77     48
4          5.65      4
5       1037.42     15
6         15.97     48
7         18.17     18
8        282.94     39
9          9.85     49
10        16.05     34
11        10.00     50
12     21513.13     50
13        10.00     20
14        11.30     28
15        18.94     43
16        16.00      9
17        26.80     20
18        17.08     48
19        10.06     38
20        16.29     27
21        22.69     36
22        14.41     42
23     24108.96      3
24        17.93     44
25        16.44     47
26       234.91      7
27        16.55     17
28         8.08     33
29        11.06     45
...         ...    ...
2315       6.13     38
2316     580.45     26
2317     551.96      1
2318      18.96     16
2319      18.24     42
2320     291.09     14
2321     212.57     26
2322   24285.01     24
2323     279.58     35
2324      18.78     47
2325      10.52     50
2326   20753.82     16
2327     280.21      5
2328   24620.37      9
2329     274.41     34
2330      15.70     37
2331      15.61     15
2332     691.46     20
2333     540.11      4
2334     643.12     20
2335       7.11      6
2336      10.13     11
2337   22111.53     31
2338     619.10     27
2339      10.98      2
2340      16.56     42
2341      10.39     36
2342      16.75     27
2343     897.07      9
2344      11.85     16

[2345 rows x 2 columns]

In [35]:
# applymap for df
sales_data[['unitprice', 'units']].applymap(lambda x: np.round(4 * x, 2)).head(5)

unitprice  units
0      47.24    108
1    1138.84      4
2      40.00    196
3      67.08    192
4      22.60     16

In [36]:
sales_data[['unitprice', 'units']].apply(lambda x: np.round(4 * x, 2)).head(5)

unitprice  units
0      47.24    108
1    1138.84      4
2      40.00    196
3      67.08    192
4      22.60     16

#####  Differences of **`.map(), .apply() .applymap()`**

 * **`.map()`**
 >iterate over each element of a DataFrame

In [37]:
sales_data['unitprice'].map(int)[:5]

0     11
1    284
2     10
3     16
4      5
Name: unitprice, dtype: int64

 * **`.apply()`**
 > apply a fucntion on an axis of the DataFrame.

e.g. sum up two cells (hier: unitprice + units)

In [38]:
sales_data[['unitprice', 'units']].apply(sum, axis=1)[:5]# default axis=0

0     38.81
1    285.71
2     59.00
3     64.77
4      9.65
dtype: float64

 * **`.applymap()`** 
 > apply a function on each element of the DataFrame

In [39]:
sales_data[['unitprice', 'units']].applymap(int)[:5]

unitprice  units
0         11     27
1        284      1
2         10     49
3         16     48
4          5      4

#### Remember: a copy of the DF is returned. The DF is not altered.

In [40]:
sales_data.head(5)

birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene 2016-10-02 08:21:20.544643   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month year-month  
0          Star Wars      11.81     27    318.87  2016     10    2016-10  
1        PlayStation     284.71      1    284.71  2016      9    2016-09  
2             banana      10.00     49    490.00  2016     10    2016-10  
3    Thriller record      16.77     48    804.96  2016     10    2016-10  
4  Harry Potter book       5.65      4     22.60  2016     10    2016-10

In [41]:
sales_data['unitprice'] = sales_data['unitprice'].map(lambda x: x * 2)

In [42]:
sales_data.describe()

unitprice        units      turnover    year        month
count   2345.000000  2345.000000  2.345000e+03  2345.0  2345.000000
mean    4659.362687    25.808102  5.991565e+04  2016.0     9.812793
std    13164.655228    14.474110  1.969636e+05     0.0     0.390161
min       10.020000     1.000000  5.080000e+00  2016.0     9.000000
25%       21.320000    13.000000  2.601000e+02  2016.0    10.000000
50%       35.700000    26.000000  5.321400e+02  2016.0    10.000000
75%      979.880000    39.000000  1.016450e+04  2016.0    10.000000
max    49791.260000    50.000000  1.222270e+06  2016.0    10.000000

In [43]:
sales_data['birthday'].describe()

count                    2345
unique                    296
top       1998-04-20 00:00:00
freq                       19
first     1952-02-07 00:00:00
last      1999-05-01 00:00:00
Name: birthday, dtype: object

In [44]:
sales_data['turnover'] = sales_data['turnover'].astype(np.int)
sales_data.head(5)

birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene 2016-10-02 08:21:20.544643   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month year-month  
0          Star Wars      23.62     27       318  2016     10    2016-10  
1        PlayStation     569.42      1       284  2016      9    2016-09  
2             banana      20.00     49       490  2016     10    2016-10  
3    Thriller record      33.54     48       804  2016     10    2016-10  
4  Harry Potter book      11.30      4        22  2016     10    2016-10

In [49]:
# sneak in NaN
sales_data.set_value(1, 'unitprice', np.NaN)
sales_data.set_value(4, 'unitprice', np.NaN)
sales_data.set_value(3, 'orderdate', np.NaN)
sales_data.head(5)

/Users/hendorf/anaconda/envs/pydata-pandas-workshop/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  
/Users/hendorf/anaconda/envs/pydata-pandas-workshop/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/hendorf/anaconda/envs/pydata-pandas-workshop/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  after removing the cwd from sys.path.


birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene                        NaT   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month year-month  
0          Star Wars      23.62     27       318  2016     10    2016-10  
1        PlayStation        NaN      1       284  2016      9    2016-09  
2             banana      20.00     49       490  2016     10    2016-10  
3    Thriller record      33.54     48       804  2016     10    2016-10  
4  Harry Potter book        NaN      4        22  2016     10    2016-10

In [50]:
# sneak in NaN
sales_data.at[1, 'unitprice'] = np.NaN
sales_data.at[4, 'unitprice'] = np.NaN
sales_data.at[3, 'orderdate'] = np.NaN
sales_data.head(5)

birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene                        NaT   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month year-month  
0          Star Wars      23.62     27       318  2016     10    2016-10  
1        PlayStation        NaN      1       284  2016      9    2016-09  
2             banana      20.00     49       490  2016     10    2016-10  
3    Thriller record      33.54     48       804  2016     10    2016-10  
4  Harry Potter book        NaN      4        22  2016     10    2016-10

In [51]:
sales_data[sales_data['unitprice'].isnull()]

birthday              customer    name                  orderdate  \
1 1986-02-05  Bell Telecom Limited   Queen 2016-09-30 08:21:20.544599   
4 1984-12-14          Frontier Inc  Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month year-month  
1        PlayStation        NaN      1       284  2016      9    2016-09  
4  Harry Potter book        NaN      4        22  2016     10    2016-10

In [52]:
sales_data.dropna().head(5)

birthday             customer      name                  orderdate  \
0 1974-01-07  Frontier Industries   Ernesto 2016-10-06 08:21:20.544568   
2 1982-07-06          Software Co      Reid 2016-10-05 08:21:20.544622   
5 1987-08-06   Internet Alpha Inc     Verna 2016-10-03 08:21:20.544687   
6 1962-10-10    Galaxy Industries    Stacia 2016-10-08 08:21:20.544707   
7 1979-03-02         Alpha Agency  Migdalia 2016-09-29 08:21:20.544726   

        product  unitprice  units  turnover  year  month year-month  
0     Star Wars      23.62     27       318  2016     10    2016-10  
2        banana      20.00     49       490  2016     10    2016-10  
5          iPad    2074.84     15     15561  2016     10    2016-10  
6  Rubik’s Cube      31.94     48       766  2016     10    2016-10  
7  Rubik’s Cube      36.34     18       327  2016      9    2016-09

In [53]:
sales_data.head(5)

birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene                        NaT   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month year-month  
0          Star Wars      23.62     27       318  2016     10    2016-10  
1        PlayStation        NaN      1       284  2016      9    2016-09  
2             banana      20.00     49       490  2016     10    2016-10  
3    Thriller record      33.54     48       804  2016     10    2016-10  
4  Harry Potter book        NaN      4        22  2016     10    2016-10

In [54]:
sales_data.fillna(99.99).head(5)

birthday               customer     name                   orderdate  \
0 1974-01-07    Frontier Industries  Ernesto  2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen  2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid  2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene                       99.99   
4 1984-12-14           Frontier Inc   Nikita  2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month year-month  
0          Star Wars      23.62     27       318  2016     10    2016-10  
1        PlayStation      99.99      1       284  2016      9    2016-09  
2             banana      20.00     49       490  2016     10    2016-10  
3    Thriller record      33.54     48       804  2016     10    2016-10  
4  Harry Potter book      99.99      4        22  2016     10    2016-10

In [55]:
sales_data.head()

birthday               customer     name                  orderdate  \
0 1974-01-07    Frontier Industries  Ernesto 2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen 2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid 2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene                        NaT   
4 1984-12-14           Frontier Inc   Nikita 2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month year-month  
0          Star Wars      23.62     27       318  2016     10    2016-10  
1        PlayStation        NaN      1       284  2016      9    2016-09  
2             banana      20.00     49       490  2016     10    2016-10  
3    Thriller record      33.54     48       804  2016     10    2016-10  
4  Harry Potter book        NaN      4        22  2016     10    2016-10

In [56]:
sales_data.fillna(99.99, inplace=True)
sales_data.head(5)

birthday               customer     name                   orderdate  \
0 1974-01-07    Frontier Industries  Ernesto  2016-10-06 08:21:20.544568   
1 1986-02-05   Bell Telecom Limited    Queen  2016-09-30 08:21:20.544599   
2 1982-07-06            Software Co     Reid  2016-10-05 08:21:20.544622   
3 1971-04-12  Data Design Galaxy Co   Arlene                       99.99   
4 1984-12-14           Frontier Inc   Nikita  2016-10-16 08:21:20.544666   

             product  unitprice  units  turnover  year  month year-month  
0          Star Wars      23.62     27       318  2016     10    2016-10  
1        PlayStation      99.99      1       284  2016      9    2016-09  
2             banana      20.00     49       490  2016     10    2016-10  
3    Thriller record      33.54     48       804  2016     10    2016-10  
4  Harry Potter book      99.99      4        22  2016     10    2016-10