In [36]:
import pandas as pd
import random
import numpy as np
import matplotlib
% matplotlib inline

In [2]:
df = pd.read_json('../data/sampledf.json')
df.index = ["R{:02d}".format(i) for i in range(len(df))]
df.columns = ["C{:02d}".format(i) for i in range(len(df.columns))]
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09
R00   79   19   21   99   35   59   44   25   75   58
R01   25   39   89   66    9   41    6   69   63    3
R02   37   64   31   69   61   97    5   11   76   57
R03   74   61  100    6   58   80   95   50   15   51
R04   79   60   83   85   16    5   16   69    5   20
R05   45   26   73   73  100   60   21   19   95   12
R06   12   29   18   98   62   68   92   29   74   96
R07   36   32   22    4   66   25   63   51   59   14
R08   55   53   89   13   84   87   74    3    2   64
R09   46   74   36   54   21   12   68   33   80   25

### Adding new Series to a DataFrame

In [3]:
df['C10'] = [random.randint(1, 100) for i in range(len(df))]
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58    3
R01   25   39   89   66    9   41    6   69   63    3   94
R02   37   64   31   69   61   97    5   11   76   57   47
R03   74   61  100    6   58   80   95   50   15   51   39
R04   79   60   83   85   16    5   16   69    5   20   22
R05   45   26   73   73  100   60   21   19   95   12   96
R06   12   29   18   98   62   68   92   29   74   96   89
R07   36   32   22    4   66   25   63   51   59   14   64
R08   55   53   89   13   84   87   74    3    2   64   76
R09   46   74   36   54   21   12   68   33   80   25   52

In [4]:
# caveat when adding a Series:
new_series = pd.Series(list([random.randint(1, 100) for i in range(len(df))]))

In [5]:
df['C10'] = new_series
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58  NaN
R01   25   39   89   66    9   41    6   69   63    3  NaN
R02   37   64   31   69   61   97    5   11   76   57  NaN
R03   74   61  100    6   58   80   95   50   15   51  NaN
R04   79   60   83   85   16    5   16   69    5   20  NaN
R05   45   26   73   73  100   60   21   19   95   12  NaN
R06   12   29   18   98   62   68   92   29   74   96  NaN
R07   36   32   22    4   66   25   63   51   59   14  NaN
R08   55   53   89   13   84   87   74    3    2   64  NaN
R09   46   74   36   54   21   12   68   33   80   25  NaN

In [6]:
# adding a new Series: mind the index of the the DF
new_series.index = df.index
df['C10'] = new_series
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58   25
R01   25   39   89   66    9   41    6   69   63    3   15
R02   37   64   31   69   61   97    5   11   76   57    7
R03   74   61  100    6   58   80   95   50   15   51   13
R04   79   60   83   85   16    5   16   69    5   20   87
R05   45   26   73   73  100   60   21   19   95   12   74
R06   12   29   18   98   62   68   92   29   74   96   38
R07   36   32   22    4   66   25   63   51   59   14   51
R08   55   53   89   13   84   87   74    3    2   64   93
R09   46   74   36   54   21   12   68   33   80   25   96

In [53]:
df['C11'] = new_series
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10  C11
R00   79   19   21   99   35   59   44   25   75   58   25   25
R01   25   39   89   66    9   41    6   69   63    3   15   15
R02   37   64   31   69   61   97    5   11   76   57    7    7
R03   74   61  100    6   58   80   95   50   15   51   13   13
R04   79   60   83   85   16    5   16   69    5   20   87   87
R05   45   26   73   73  100   60   21   19   95   12   74   74
R06   12   29   18   98   62   68   92   29   74   96   38   38
R07   36   32   22    4   66   25   63   51   59   14   51   51
R08   55   53   89   13   84   87   74    3    2   64   93   93
R09   46   74   36   54   21   12   68   33   80   25   96   96

In [54]:
del df['C11']
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58   25
R01   25   39   89   66    9   41    6   69   63    3   15
R02   37   64   31   69   61   97    5   11   76   57    7
R03   74   61  100    6   58   80   95   50   15   51   13
R04   79   60   83   85   16    5   16   69    5   20   87
R05   45   26   73   73  100   60   21   19   95   12   74
R06   12   29   18   98   62   68   92   29   74   96   38
R07   36   32   22    4   66   25   63   51   59   14   51
R08   55   53   89   13   84   87   74    3    2   64   93
R09   46   74   36   54   21   12   68   33   80   25   96

In [59]:
del df['C12']

KeyError: 'C12'

In [58]:
# avoid KeyErrors if unsure Series exists
df.drop(['C12'], errors='ignore')

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58   25
R01   25   39   89   66    9   41    6   69   63    3   15
R02   37   64   31   69   61   97    5   11   76   57    7
R03   74   61  100    6   58   80   95   50   15   51   13
R04   79   60   83   85   16    5   16   69    5   20   87
R05   45   26   73   73  100   60   21   19   95   12   74
R06   12   29   18   98   62   68   92   29   74   96   38
R07   36   32   22    4   66   25   63   51   59   14   51
R08   55   53   89   13   84   87   74    3    2   64   93
R09   46   74   36   54   21   12   68   33   80   25   96

**recall: NumPy Broadcasting**

In [11]:
a = np.random.rand(3,1)
a

array([[ 0.41382987],
       [ 0.40752664],
       [ 0.06252347]])

In [12]:
b = np.random.rand(3,1)
b

array([[ 0.4964604 ],
       [ 0.78639947],
       [ 0.00602112]])

In [13]:
a + b

array([[ 0.91029027],
       [ 1.19392611],
       [ 0.06854459]])

In [16]:
a - b

array([[-0.08263052],
       [-0.37887283],
       [ 0.05650235]])

In [14]:
a * b

array([[ 0.20545014],
       [ 0.32047874],
       [ 0.00037646]])

In [15]:
a / b

array([[  0.8335607 ],
       [  0.51821836],
       [ 10.38403157]])

In [17]:
a + 7

array([[ 7.41382987],
       [ 7.40752664],
       [ 7.06252347]])

In [19]:
b // 2

array([[ 0.],
       [ 0.],
       [ 0.]])

In [20]:
a % 2 == 0

array([[False],
       [False],
       [False]], dtype=bool)

In [22]:
a * [4, 5]

array([[ 1.65531949,  2.06914937],
       [ 1.63010657,  2.03763322],
       [ 0.25009388,  0.31261735]])

### Pandas

In [29]:
sales_data = pd.read_json('../data/blooth_sales_data.json',
                              convert_dates=['birthday', 'orderdate']
                              )
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units  
0 2016-07-17 13:48:03.156566    Thriller record      13.27      2  
1 2016-07-06 13:48:03.156596            Corolla   24458.69     26  
2 2016-07-22 13:48:03.156618       Rubik’s Cube      15.79     41  
3 2016-07-23 13:48:03.156638             iPhone     584.01     16  
4 2016-07-16 13:48:03.156657  Harry Potter book      25.69      4

In [30]:
sales_data['turnover'] = sales_data['unitprice'] * sales_data['units']
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units   turnover  
0 2016-07-17 13:48:03.156566    Thriller record      13.27      2      26.54  
1 2016-07-06 13:48:03.156596            Corolla   24458.69     26  635925.94  
2 2016-07-22 13:48:03.156618       Rubik’s Cube      15.79     41     647.39  
3 2016-07-23 13:48:03.156638             iPhone     584.01     16    9344.16  
4 2016-07-16 13:48:03.156657  Harry Potter book      25.69      4     102.76

In [32]:
sales_data['turnover'].mean()

57794.30212

In [33]:
sales_data.mean()

unitprice     2202.87399
units           25.84200
turnover     57794.30212
dtype: float64

In [41]:
sales_data['turnover'].median()

560.3799999999999

In [45]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 8 columns):
birthday     1000 non-null datetime64[ns]
customer     1000 non-null object
name         1000 non-null object
orderdate    1000 non-null datetime64[ns]
product      1000 non-null object
unitprice    1000 non-null float64
units        1000 non-null int64
turnover     1000 non-null float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(3)
memory usage: 110.3+ KB


In [46]:
# map for Series
sales_data['year'] = sales_data['orderdate'].map(lambda x: x.year)
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units   turnover  \
0 2016-07-17 13:48:03.156566    Thriller record      13.27      2      26.54   
1 2016-07-06 13:48:03.156596            Corolla   24458.69     26  635925.94   
2 2016-07-22 13:48:03.156618       Rubik’s Cube      15.79     41     647.39   
3 2016-07-23 13:48:03.156638             iPhone     584.01     16    9344.16   
4 2016-07-16 13:48:03.156657  Harry Potter book      25.69      4     102.76   

   year  
0  2016  
1  2016  
2  2016  
3  2016  
4  2016

In [99]:
# map for Series
sales_data['month'] = sales_data['orderdate'].map(lambda x: x.month)
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                      orderdate            product  unitprice  units  \
0 2016-07-17 13:48:03.156566000    Thriller record      26.54      2   
1 2016-07-06 13:48:03.156596000            Corolla      99.99     26   
2 2016-07-22 13:48:03.156618000       Rubik’s Cube      31.58     41   
3 1970-01-01 00:00:00.000000099             iPhone    1168.02     16   
4 2016-07-16 13:48:03.156657000  Harry Potter book      99.99      4   

   turnover  year  month  
0        26  2016      7  
1    635925  2016      7  
2       647  2016      7  
3      9344  2016      1  
4       102  2016      7

In [103]:
# combine multiple columns
sales_data['year-month'] = sales_data['year'].map(
    str) + sales_data['month'].map(lambda x: "-{:02d}".format(x))

In [102]:
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                      orderdate            product  unitprice  units  \
0 2016-07-17 13:48:03.156566000    Thriller record      26.54      2   
1 2016-07-06 13:48:03.156596000            Corolla      99.99     26   
2 2016-07-22 13:48:03.156618000       Rubik’s Cube      31.58     41   
3 1970-01-01 00:00:00.000000099             iPhone    1168.02     16   
4 2016-07-16 13:48:03.156657000  Harry Potter book      99.99      4   

   turnover  year  month year-month  
0        26  2016      7    2016-07  
1    635925  2016      7    2016-07  
2       647  2016      7    2016-07  
3      9344  2016      1    2016-01  
4       102  2016      7    2016-07

In [50]:
# applymap for df
sales_data[['unitprice', 'units']].applymap(lambda x: x / 1.5).head(5)

unitprice      units
0      8.846667   1.333333
1  16305.793333  17.333333
2     10.526667  27.333333
3    389.340000  10.666667
4     17.126667   2.666667

In [51]:
# remember: a copy of the DF is returned. The DF is not altered.
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units   turnover  \
0 2016-07-17 13:48:03.156566    Thriller record      13.27      2      26.54   
1 2016-07-06 13:48:03.156596            Corolla   24458.69     26  635925.94   
2 2016-07-22 13:48:03.156618       Rubik’s Cube      15.79     41     647.39   
3 2016-07-23 13:48:03.156638             iPhone     584.01     16    9344.16   
4 2016-07-16 13:48:03.156657  Harry Potter book      25.69      4     102.76   

   year  
0  2016  
1  2016  
2  2016  
3  2016  
4  2016

In [52]:
sales_data['unitprice'] = sales_data['unitprice'].map(lambda x: x * 2)

In [60]:
sales_data.describe()

unitprice        units      turnover    year
count   1000.000000  1000.000000  1.000000e+03  1000.0
mean    4405.747980    25.842000  5.779430e+04  2016.0
std    12739.726665    14.581689  1.948077e+05     0.0
min       10.040000     1.000000  1.000000e+01  2016.0
25%       21.550000    13.000000  2.600000e+02  2016.0
50%       36.010000    26.000000  5.603800e+02  2016.0
75%     1017.960000    39.000000  9.991180e+03  2016.0
max    49934.620000    50.000000  1.206765e+06  2016.0

In [61]:
sales_data['birthday'].describe()

count                    1000
unique                    284
top       1986-11-05 00:00:00
freq                       10
first     1951-10-15 00:00:00
last      1998-12-29 00:00:00
Name: birthday, dtype: object

In [64]:
sales_data['turnover'] = sales_data['turnover'].astype(np.int)
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units  turnover  \
0 2016-07-17 13:48:03.156566    Thriller record      26.54      2        26   
1 2016-07-06 13:48:03.156596            Corolla   48917.38     26    635925   
2 2016-07-22 13:48:03.156618       Rubik’s Cube      31.58     41       647   
3 2016-07-23 13:48:03.156638             iPhone    1168.02     16      9344   
4 2016-07-16 13:48:03.156657  Harry Potter book      51.38      4       102   

   year  
0  2016  
1  2016  
2  2016  
3  2016  
4  2016

In [88]:
# sneak in NaN
sales_data.set_value(1, 'unitprice', np.NaN)
sales_data.set_value(4, 'unitprice', np.NaN)
sales_data.set_value(3, 'orderdate', np.NaN)
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units  turnover  \
0 2016-07-17 13:48:03.156566    Thriller record      26.54      2        26   
1 2016-07-06 13:48:03.156596            Corolla        NaN     26    635925   
2 2016-07-22 13:48:03.156618       Rubik’s Cube      31.58     41       647   
3                        NaT             iPhone    1168.02     16      9344   
4 2016-07-16 13:48:03.156657  Harry Potter book        NaN      4       102   

   year  
0  2016  
1  2016  
2  2016  
3  2016  
4  2016

In [93]:
sales_data[sales_data['unitprice'].isnull()]

birthday                    customer   name                  orderdate  \
1 1968-12-13  Electronics Resource Group  India 2016-07-06 13:48:03.156596   
4 1972-04-23       Star Alpha Industries  Chang 2016-07-16 13:48:03.156657   

             product  unitprice  units  turnover  year  
1            Corolla        NaN     26    635925  2016  
4  Harry Potter book        NaN      4       102  2016

In [94]:
sales_data.dropna().head(5)

birthday                           customer      name  \
0 1967-09-02                    Electronics Inc  Pasquale   
2 1992-09-10      East Application Contract Inc     Wayne   
5 1953-03-17             Network Application Co    Weldon   
6 1977-10-23  Omega Pacific Future Incorporated      Sung   
7 1982-07-02              Medicine Incorporated     Emily   

                   orderdate          product  unitprice  units  turnover  \
0 2016-07-17 13:48:03.156566  Thriller record      26.54      2        26   
2 2016-07-22 13:48:03.156618     Rubik’s Cube      31.58     41       647   
5 2016-07-22 13:48:03.156678          Lipitor      22.44      1        11   
6 2016-07-09 13:48:03.156698      PlayStation     589.80     25      7372   
7 2016-07-16 13:48:03.156717  Thriller record      36.54      5        91   

   year  
0  2016  
2  2016  
5  2016  
6  2016  
7  2016

In [95]:
sales_data.fillna(99.99).head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                      orderdate            product  unitprice  units  \
0 2016-07-17 13:48:03.156566000    Thriller record      26.54      2   
1 2016-07-06 13:48:03.156596000            Corolla      99.99     26   
2 2016-07-22 13:48:03.156618000       Rubik’s Cube      31.58     41   
3 1970-01-01 00:00:00.000000099             iPhone    1168.02     16   
4 2016-07-16 13:48:03.156657000  Harry Potter book      99.99      4   

   turnover  year  
0        26  2016  
1    635925  2016  
2       647  2016  
3      9344  2016  
4       102  2016

In [96]:
sales_data.head()

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units  turnover  \
0 2016-07-17 13:48:03.156566    Thriller record      26.54      2        26   
1 2016-07-06 13:48:03.156596            Corolla        NaN     26    635925   
2 2016-07-22 13:48:03.156618       Rubik’s Cube      31.58     41       647   
3                        NaT             iPhone    1168.02     16      9344   
4 2016-07-16 13:48:03.156657  Harry Potter book        NaN      4       102   

   year  
0  2016  
1  2016  
2  2016  
3  2016  
4  2016

In [98]:
sales_data.fillna(99.99, inplace=True)
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                      orderdate            product  unitprice  units  \
0 2016-07-17 13:48:03.156566000    Thriller record      26.54      2   
1 2016-07-06 13:48:03.156596000            Corolla      99.99     26   
2 2016-07-22 13:48:03.156618000       Rubik’s Cube      31.58     41   
3 1970-01-01 00:00:00.000000099             iPhone    1168.02     16   
4 2016-07-16 13:48:03.156657000  Harry Potter book      99.99      4   

   turnover  year  
0        26  2016  
1    635925  2016  
2       647  2016  
3      9344  2016  
4       102  2016