In [1]:
import pandas as pd
import random
import numpy as np
import matplotlib
% matplotlib inline

In [2]:
df = pd.read_json('../data/sampledf.json')
df.index = ["R{:02d}".format(i) for i in range(len(df))]
df.columns = ["C{:02d}".format(i) for i in range(len(df.columns))]
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09
R00   79   19   21   99   35   59   44   25   75   58
R01   25   39   89   66    9   41    6   69   63    3
R02   37   64   31   69   61   97    5   11   76   57
R03   74   61  100    6   58   80   95   50   15   51
R04   79   60   83   85   16    5   16   69    5   20
R05   45   26   73   73  100   60   21   19   95   12
R06   12   29   18   98   62   68   92   29   74   96
R07   36   32   22    4   66   25   63   51   59   14
R08   55   53   89   13   84   87   74    3    2   64
R09   46   74   36   54   21   12   68   33   80   25

### Adding and deleting Series in a DataFrame

In [3]:
df['C10'] = [random.randint(1, 100) for i in range(len(df))]
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58   43
R01   25   39   89   66    9   41    6   69   63    3   99
R02   37   64   31   69   61   97    5   11   76   57   16
R03   74   61  100    6   58   80   95   50   15   51    4
R04   79   60   83   85   16    5   16   69    5   20   92
R05   45   26   73   73  100   60   21   19   95   12   56
R06   12   29   18   98   62   68   92   29   74   96   55
R07   36   32   22    4   66   25   63   51   59   14   73
R08   55   53   89   13   84   87   74    3    2   64   25
R09   46   74   36   54   21   12   68   33   80   25   93

In [4]:
# caveat when adding a Series:
new_series = pd.Series(list([random.randint(1, 100) for i in range(len(df))]))
new_series

0     9
1     4
2    29
3    47
4    61
5    76
6    76
7    96
8    89
9    98
dtype: int64

In [5]:
df['C10'] = new_series
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58  NaN
R01   25   39   89   66    9   41    6   69   63    3  NaN
R02   37   64   31   69   61   97    5   11   76   57  NaN
R03   74   61  100    6   58   80   95   50   15   51  NaN
R04   79   60   83   85   16    5   16   69    5   20  NaN
R05   45   26   73   73  100   60   21   19   95   12  NaN
R06   12   29   18   98   62   68   92   29   74   96  NaN
R07   36   32   22    4   66   25   63   51   59   14  NaN
R08   55   53   89   13   84   87   74    3    2   64  NaN
R09   46   74   36   54   21   12   68   33   80   25  NaN

In [6]:
# adding a new Series: mind the index of the the DF
new_series.index = df.index
new_series

R00     9
R01     4
R02    29
R03    47
R04    61
R05    76
R06    76
R07    96
R08    89
R09    98
dtype: int64

In [7]:
df['C10'] = new_series
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58    9
R01   25   39   89   66    9   41    6   69   63    3    4
R02   37   64   31   69   61   97    5   11   76   57   29
R03   74   61  100    6   58   80   95   50   15   51   47
R04   79   60   83   85   16    5   16   69    5   20   61
R05   45   26   73   73  100   60   21   19   95   12   76
R06   12   29   18   98   62   68   92   29   74   96   76
R07   36   32   22    4   66   25   63   51   59   14   96
R08   55   53   89   13   84   87   74    3    2   64   89
R09   46   74   36   54   21   12   68   33   80   25   98

In [8]:
df['C11'] = new_series
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10  C11
R00   79   19   21   99   35   59   44   25   75   58    9    9
R01   25   39   89   66    9   41    6   69   63    3    4    4
R02   37   64   31   69   61   97    5   11   76   57   29   29
R03   74   61  100    6   58   80   95   50   15   51   47   47
R04   79   60   83   85   16    5   16   69    5   20   61   61
R05   45   26   73   73  100   60   21   19   95   12   76   76
R06   12   29   18   98   62   68   92   29   74   96   76   76
R07   36   32   22    4   66   25   63   51   59   14   96   96
R08   55   53   89   13   84   87   74    3    2   64   89   89
R09   46   74   36   54   21   12   68   33   80   25   98   98

In [9]:
del df['C11']
df

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58    9
R01   25   39   89   66    9   41    6   69   63    3    4
R02   37   64   31   69   61   97    5   11   76   57   29
R03   74   61  100    6   58   80   95   50   15   51   47
R04   79   60   83   85   16    5   16   69    5   20   61
R05   45   26   73   73  100   60   21   19   95   12   76
R06   12   29   18   98   62   68   92   29   74   96   76
R07   36   32   22    4   66   25   63   51   59   14   96
R08   55   53   89   13   84   87   74    3    2   64   89
R09   46   74   36   54   21   12   68   33   80   25   98

In [10]:
del df['C12']

KeyError: 'C12'

In [11]:
# avoid KeyErrors if unsure Series exists
df.drop(['C12'], errors='ignore')

C00  C01  C02  C03  C04  C05  C06  C07  C08  C09  C10
R00   79   19   21   99   35   59   44   25   75   58    9
R01   25   39   89   66    9   41    6   69   63    3    4
R02   37   64   31   69   61   97    5   11   76   57   29
R03   74   61  100    6   58   80   95   50   15   51   47
R04   79   60   83   85   16    5   16   69    5   20   61
R05   45   26   73   73  100   60   21   19   95   12   76
R06   12   29   18   98   62   68   92   29   74   96   76
R07   36   32   22    4   66   25   63   51   59   14   96
R08   55   53   89   13   84   87   74    3    2   64   89
R09   46   74   36   54   21   12   68   33   80   25   98

In [12]:
# getting a subset is simpler than delting many columns
dfs = df.loc[:, ['C03', 'C05']]
dfs

C03  C05
R00   99   59
R01   66   41
R02   69   97
R03    6   80
R04   85    5
R05   73   60
R06   98   68
R07    4   25
R08   13   87
R09   54   12

### Mangle your data

**recall: NumPy Broadcasting**

In [13]:
a = np.random.rand(3,1)
a

array([[ 0.99623465],
       [ 0.76192045],
       [ 0.39202932]])

In [14]:
b = np.random.rand(3,1)
b

array([[ 0.60215528],
       [ 0.90448681],
       [ 0.91638643]])

In [15]:
a + b

array([[ 1.59838993],
       [ 1.66640726],
       [ 1.30841575]])

In [16]:
a - b

array([[ 0.39407937],
       [-0.14256636],
       [-0.52435711]])

In [17]:
a * b

array([[ 0.59988796],
       [ 0.689147  ],
       [ 0.35925035]])

In [18]:
a / b

array([[ 1.65444808],
       [ 0.84237873],
       [ 0.42779913]])

In [19]:
a + 7

array([[ 7.99623465],
       [ 7.76192045],
       [ 7.39202932]])

In [20]:
b // 2

array([[ 0.],
       [ 0.],
       [ 0.]])

In [21]:
a % 2 == 0

array([[False],
       [False],
       [False]], dtype=bool)

In [22]:
a * [4, 5]

array([[ 3.98493859,  4.98117324],
       [ 3.04768181,  3.80960226],
       [ 1.56811727,  1.96014659]])

### Pandas

In [23]:
sales_data = pd.read_json('../data/blooth_sales_data.json',
                              convert_dates=['birthday', 'orderdate']
                              )
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units  
0 2016-07-17 13:48:03.156566    Thriller record      13.27      2  
1 2016-07-06 13:48:03.156596            Corolla   24458.69     26  
2 2016-07-22 13:48:03.156618       Rubik’s Cube      15.79     41  
3 2016-07-23 13:48:03.156638             iPhone     584.01     16  
4 2016-07-16 13:48:03.156657  Harry Potter book      25.69      4

In [24]:
sales_data['turnover'] = sales_data['unitprice'] * sales_data['units']
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units   turnover  
0 2016-07-17 13:48:03.156566    Thriller record      13.27      2      26.54  
1 2016-07-06 13:48:03.156596            Corolla   24458.69     26  635925.94  
2 2016-07-22 13:48:03.156618       Rubik’s Cube      15.79     41     647.39  
3 2016-07-23 13:48:03.156638             iPhone     584.01     16    9344.16  
4 2016-07-16 13:48:03.156657  Harry Potter book      25.69      4     102.76

In [25]:
sales_data['turnover'].mean()

57794.30212

In [26]:
sales_data.mean()

unitprice     2202.87399
units           25.84200
turnover     57794.30212
dtype: float64

In [27]:
sales_data['turnover'].sum()

57794302.119999997

In [ ]:
sales_data['turnover'].median()

In [28]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 8 columns):
birthday     1000 non-null datetime64[ns]
customer     1000 non-null object
name         1000 non-null object
orderdate    1000 non-null datetime64[ns]
product      1000 non-null object
unitprice    1000 non-null float64
units        1000 non-null int64
turnover     1000 non-null float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(3)
memory usage: 70.3+ KB


In [29]:
# map for Series
sales_data['year'] = sales_data['orderdate'].map(lambda x: x.year)
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units   turnover  \
0 2016-07-17 13:48:03.156566    Thriller record      13.27      2      26.54   
1 2016-07-06 13:48:03.156596            Corolla   24458.69     26  635925.94   
2 2016-07-22 13:48:03.156618       Rubik’s Cube      15.79     41     647.39   
3 2016-07-23 13:48:03.156638             iPhone     584.01     16    9344.16   
4 2016-07-16 13:48:03.156657  Harry Potter book      25.69      4     102.76   

   year  
0  2016  
1  2016  
2  2016  
3  2016  
4  2016

In [30]:
# map for Series
sales_data['month'] = sales_data['orderdate'].map(lambda x: x.month)
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units   turnover  \
0 2016-07-17 13:48:03.156566    Thriller record      13.27      2      26.54   
1 2016-07-06 13:48:03.156596            Corolla   24458.69     26  635925.94   
2 2016-07-22 13:48:03.156618       Rubik’s Cube      15.79     41     647.39   
3 2016-07-23 13:48:03.156638             iPhone     584.01     16    9344.16   
4 2016-07-16 13:48:03.156657  Harry Potter book      25.69      4     102.76   

   year  month  
0  2016      7  
1  2016      7  
2  2016      7  
3  2016      7  
4  2016      7

In [31]:
# combine multiple columns
sales_data['year-month'] = sales_data['year'].map(
    str) + sales_data['month'].map(lambda x: "-{:02d}".format(x))

In [32]:
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units   turnover  \
0 2016-07-17 13:48:03.156566    Thriller record      13.27      2      26.54   
1 2016-07-06 13:48:03.156596            Corolla   24458.69     26  635925.94   
2 2016-07-22 13:48:03.156618       Rubik’s Cube      15.79     41     647.39   
3 2016-07-23 13:48:03.156638             iPhone     584.01     16    9344.16   
4 2016-07-16 13:48:03.156657  Harry Potter book      25.69      4     102.76   

   year  month year-month  
0  2016      7    2016-07  
1  2016      7    2016-07  
2  2016      7    2016-07  
3  2016      7    2016-07  
4  2016      7    2016-07

In [34]:
sales_data[['unitprice', 'units']]

unitprice  units
0        13.27      2
1     24458.69     26
2        15.79     41
3       584.01     16
4        25.69      4
5        11.22      1
6       294.90     25
7        18.27      5
8        15.98     35
9        11.50     24
10        8.09     27
11      368.98     12
12    24870.63     43
13      242.63     43
14      646.14     41
15    23570.41      7
16       11.85      9
17      290.46     15
18       18.64      8
19       26.79     20
20       33.48     26
21      265.01     11
22       15.90     17
23      500.83     44
24       18.07     17
25       17.07     22
26      206.32     13
27    22280.90     18
28    20103.97     44
29      260.43     37
..         ...    ...
970      11.49     18
971      15.73     44
972     649.14     30
973      17.01     16
974     298.22     31
975      31.92     29
976     214.58     45
977      18.52     27
978     342.89     13
979       9.15     43
980     878.79     19
981      15.09      3
982     980.17     29
983   22776.03     50
984      11.71      6
985      11.01     39
986     333.48     46
987      12.20     28
988      10.06      8
989      28.09      6
990     782.68     35
991      10.38     22
992     875.16     40
993      10.00     19
994      10.07     27
995      24.40     39
996      15.11      9
997       9.16     19
998      28.21     24
999     663.83     39

[1000 rows x 2 columns]

In [33]:
# applymap for df
sales_data[['unitprice', 'units']].applymap(lambda x: x / 1.5).head(5)

unitprice      units
0      8.846667   1.333333
1  16305.793333  17.333333
2     10.526667  27.333333
3    389.340000  10.666667
4     17.126667   2.666667

In [35]:
sales_data[['unitprice', 'units']].apply(lambda x: x / 1.5).head(5)

unitprice      units
0      8.846667   1.333333
1  16305.793333  17.333333
2     10.526667  27.333333
3    389.340000  10.666667
4     17.126667   2.666667

In [37]:
# remember: a copy of the DF is returned. The DF is not altered.
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units   turnover  \
0 2016-07-17 13:48:03.156566    Thriller record      13.27      2      26.54   
1 2016-07-06 13:48:03.156596            Corolla   24458.69     26  635925.94   
2 2016-07-22 13:48:03.156618       Rubik’s Cube      15.79     41     647.39   
3 2016-07-23 13:48:03.156638             iPhone     584.01     16    9344.16   
4 2016-07-16 13:48:03.156657  Harry Potter book      25.69      4     102.76   

   year  month year-month  
0  2016      7    2016-07  
1  2016      7    2016-07  
2  2016      7    2016-07  
3  2016      7    2016-07  
4  2016      7    2016-07

In [38]:
sales_data['unitprice'] = sales_data['unitprice'].map(lambda x: x * 2)

In [39]:
sales_data.describe()

unitprice        units      turnover    year       month
count   1000.000000  1000.000000  1.000000e+03  1000.0  1000.00000
mean    4405.747980    25.842000  5.779430e+04  2016.0     6.96600
std    12739.726665    14.581689  1.948077e+05     0.0     0.18132
min       10.040000     1.000000  1.000000e+01  2016.0     6.00000
25%       21.550000    13.000000  2.600000e+02  2016.0     7.00000
50%       36.010000    26.000000  5.603800e+02  2016.0     7.00000
75%     1017.960000    39.000000  9.991180e+03  2016.0     7.00000
max    49934.620000    50.000000  1.206765e+06  2016.0     7.00000

In [40]:
sales_data['birthday'].describe()

count                    1000
unique                    284
top       1986-11-05 00:00:00
freq                       10
first     1951-10-15 00:00:00
last      1998-12-29 00:00:00
Name: birthday, dtype: object

In [41]:
sales_data['turnover'] = sales_data['turnover'].astype(np.int)
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units  turnover  \
0 2016-07-17 13:48:03.156566    Thriller record      26.54      2        26   
1 2016-07-06 13:48:03.156596            Corolla   48917.38     26    635925   
2 2016-07-22 13:48:03.156618       Rubik’s Cube      31.58     41       647   
3 2016-07-23 13:48:03.156638             iPhone    1168.02     16      9344   
4 2016-07-16 13:48:03.156657  Harry Potter book      51.38      4       102   

   year  month year-month  
0  2016      7    2016-07  
1  2016      7    2016-07  
2  2016      7    2016-07  
3  2016      7    2016-07  
4  2016      7    2016-07

In [42]:
# sneak in NaN
sales_data.set_value(1, 'unitprice', np.NaN)
sales_data.set_value(4, 'unitprice', np.NaN)
sales_data.set_value(3, 'orderdate', np.NaN)
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units  turnover  \
0 2016-07-17 13:48:03.156566    Thriller record      26.54      2        26   
1 2016-07-06 13:48:03.156596            Corolla        NaN     26    635925   
2 2016-07-22 13:48:03.156618       Rubik’s Cube      31.58     41       647   
3                        NaT             iPhone    1168.02     16      9344   
4 2016-07-16 13:48:03.156657  Harry Potter book        NaN      4       102   

   year  month year-month  
0  2016      7    2016-07  
1  2016      7    2016-07  
2  2016      7    2016-07  
3  2016      7    2016-07  
4  2016      7    2016-07

In [43]:
sales_data[sales_data['unitprice'].isnull()]

birthday                    customer   name                  orderdate  \
1 1968-12-13  Electronics Resource Group  India 2016-07-06 13:48:03.156596   
4 1972-04-23       Star Alpha Industries  Chang 2016-07-16 13:48:03.156657   

             product  unitprice  units  turnover  year  month year-month  
1            Corolla        NaN     26    635925  2016      7    2016-07  
4  Harry Potter book        NaN      4       102  2016      7    2016-07

In [44]:
sales_data.dropna().head(5)

birthday                           customer      name  \
0 1967-09-02                    Electronics Inc  Pasquale   
2 1992-09-10      East Application Contract Inc     Wayne   
5 1953-03-17             Network Application Co    Weldon   
6 1977-10-23  Omega Pacific Future Incorporated      Sung   
7 1982-07-02              Medicine Incorporated     Emily   

                   orderdate          product  unitprice  units  turnover  \
0 2016-07-17 13:48:03.156566  Thriller record      26.54      2        26   
2 2016-07-22 13:48:03.156618     Rubik’s Cube      31.58     41       647   
5 2016-07-22 13:48:03.156678          Lipitor      22.44      1        11   
6 2016-07-09 13:48:03.156698      PlayStation     589.80     25      7372   
7 2016-07-16 13:48:03.156717  Thriller record      36.54      5        91   

   year  month year-month  
0  2016      7    2016-07  
2  2016      7    2016-07  
5  2016      7    2016-07  
6  2016      7    2016-07  
7  2016      7    2016-07

In [45]:
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units  turnover  \
0 2016-07-17 13:48:03.156566    Thriller record      26.54      2        26   
1 2016-07-06 13:48:03.156596            Corolla        NaN     26    635925   
2 2016-07-22 13:48:03.156618       Rubik’s Cube      31.58     41       647   
3                        NaT             iPhone    1168.02     16      9344   
4 2016-07-16 13:48:03.156657  Harry Potter book        NaN      4       102   

   year  month year-month  
0  2016      7    2016-07  
1  2016      7    2016-07  
2  2016      7    2016-07  
3  2016      7    2016-07  
4  2016      7    2016-07

In [46]:
sales_data.fillna(99.99).head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                      orderdate            product  unitprice  units  \
0 2016-07-17 13:48:03.156566000    Thriller record      26.54      2   
1 2016-07-06 13:48:03.156596000            Corolla      99.99     26   
2 2016-07-22 13:48:03.156618000       Rubik’s Cube      31.58     41   
3 1970-01-01 00:00:00.000000099             iPhone    1168.02     16   
4 2016-07-16 13:48:03.156657000  Harry Potter book      99.99      4   

   turnover  year  month year-month  
0        26  2016      7    2016-07  
1    635925  2016      7    2016-07  
2       647  2016      7    2016-07  
3      9344  2016      7    2016-07  
4       102  2016      7    2016-07

In [47]:
sales_data.head()

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                   orderdate            product  unitprice  units  turnover  \
0 2016-07-17 13:48:03.156566    Thriller record      26.54      2        26   
1 2016-07-06 13:48:03.156596            Corolla        NaN     26    635925   
2 2016-07-22 13:48:03.156618       Rubik’s Cube      31.58     41       647   
3                        NaT             iPhone    1168.02     16      9344   
4 2016-07-16 13:48:03.156657  Harry Potter book        NaN      4       102   

   year  month year-month  
0  2016      7    2016-07  
1  2016      7    2016-07  
2  2016      7    2016-07  
3  2016      7    2016-07  
4  2016      7    2016-07

In [48]:
sales_data.fillna(99.99, inplace=True)
sales_data.head(5)

birthday                       customer      name  \
0 1967-09-02                Electronics Inc  Pasquale   
1 1968-12-13     Electronics Resource Group     India   
2 1992-09-10  East Application Contract Inc     Wayne   
3 1986-11-05              Signal Industries      Cori   
4 1972-04-23          Star Alpha Industries     Chang   

                      orderdate            product  unitprice  units  \
0 2016-07-17 13:48:03.156566000    Thriller record      26.54      2   
1 2016-07-06 13:48:03.156596000            Corolla      99.99     26   
2 2016-07-22 13:48:03.156618000       Rubik’s Cube      31.58     41   
3 1970-01-01 00:00:00.000000099             iPhone    1168.02     16   
4 2016-07-16 13:48:03.156657000  Harry Potter book      99.99      4   

   turnover  year  month year-month  
0        26  2016      7    2016-07  
1    635925  2016      7    2016-07  
2       647  2016      7    2016-07  
3      9344  2016      7    2016-07  
4       102  2016      7    2016-07